config/routes.rb
Rails.application.routes.draw do
  get 'private_realty/new'

  get 'private_realty/create'

  get 'private_realty/edit'

  get 'private_realty/update'

  get 'private_realty/index'

  get 'private_realty/show'

  get 'private_realty/destroy'

#  get 'users/show'
#
#  get 'users/edit'
#
#  get 'users/update'

	
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'realties/new'

  get 'realties/create'

  get 'realties/edit'

  get 'realties/update'

  get 'realties/index'

  get 'realties/show'

  get 'realties/destroy'

  root 'pages#home'

  get 'about' => 'pages#about'
	
	resources :realties
	resources :users
	resources :private_realty
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :realty

	has_attached_file :image,
                    styles: {medium: '200x250!', thumb: '100x100!'},
										:default_url => "path to default image"
										#:default_url => "genImage.jpg"
										#default_url: ->(attachment) { ActionController::Base.helpers.asset_path('genImage.jpg') }
										#:default_url => ActionController::Base.helpers.image_path("genImage.jpg")
										#default_url: ":style/genImage.jpg"
	
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	#validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/governorate.rb
class Governorate < ApplicationRecord
	has_many :provinces
	has_many :realties
end

app/models/luxury.rb
class Luxury < ApplicationRecord
	
	has_many :realty_luxuries, dependent: :destroy #, inverse_of: :luxury
	has_many :realties, through: :realty_luxuries#, source: :realty
	
	#accepts_nested_attributes_for :realty_luxuries
end

app/models/province.rb
class Province < ApplicationRecord
	
	belongs_to :governorate
	has_many :realties
	
end

app/models/realty.rb
class Realty < ApplicationRecord

	belongs_to :governorate
	belongs_to :province
	#belongs_to :luxury
	belongs_to :type
	belongs_to :category
	belongs_to :user
	
	has_many :assets, dependent: :destroy
	
	has_many :realty_luxuries, dependent: :destroy #, inverse_of: :realty
	has_many :luxuries, through: :realty_luxuries
	
	accepts_nested_attributes_for :assets, :reject_if => lambda { |t| t['image'].nil? }, allow_destroy: true
	


end

app/models/realty_luxury.rb
class RealtyLuxury < ApplicationRecord
  belongs_to :realty#, inverse_of: :realty_luxuries
  belongs_to :luxury#, inverse_of: :realty_luxuries
	
	#accepts_nested_attributes_for :luxury
    
end

app/models/type.rb
class Type < ApplicationRecord
	
	has_many :realties
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable
	
	has_many :realties
	
#	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
#	#, :default_url => "/images/:style/missing.png"
#  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	
	def display_name
 		return self.email
	end
	
#  def password_required?
#    if respond_to?(:reset_password_token)
#      return true if reset_password_token.present?
#    end
#    return true if new_record?
#    password.present? || password_confirmation.present?
#  end
	
def password_required?
  new_record? || password.present? || password_confirmation.present?
end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/governorates_helper.rb
module GovernoratesHelper
end

app/helpers/luxuries_helper.rb
module LuxuriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/realties_helper.rb
module RealtiesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>اليكس بروكروز</title>
    <%= csrf_meta_tags %>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :realtyShow %> 
  </head>

  <body>
   	
   	<header>
   		<%=render "partials/navbar"%>
 		</header>
  	
  	<main>
			<div class="container-fluid" id="main">
				<%= yield %>
			</div>
  	</main>		
 
   	<footer>
   		<p>مكتب اليكس بروكرز للعقارات بالاسكندرية...التسويق بمفهوم مختلف.</p>
   		<p> للإستفسار اتصل بنا علي <i class="fa fa-mobile fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp" aria-hidden="true"></i> 01223367978. <i class="fa fa-comment" aria-hidden="true"></i> @hindawy1973</p>
    	<p>Copyrite &copy; Amr El-Massry, 2017, All Rights Reserved</p>
   	</footer> 
   	 	
  </body>
</html>

app/views/pages/about.html.erb
<div class="row" >


		<div class="col-md-2" id="index-left">
			<h1>إعلانات</h1>
 			<%= render 'partials/leftAd'%>
		</div>
		
		<div class="col-md-8" id="edit-middle">

			<div id="about-main">
				
			<p>تصفح موقعنا <a href="http://www.alexbrokers.website">www.alexbrokers.website</a> للمزيد من الاختيارات.</p>
			<p><strong><a href="http://www.youtube.com/user/hindawy1973">قناة مكتب اليكس بروكرز للعقارات بالاسكندرية علي اليوتيوب.</a></strong></p>
			<p> للإستفسار اتصل بنا علي <i class="fa fa-mobile fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp" aria-hidden="true"></i> 01223367978. <i class="fa fa-comment" aria-hidden="true"></i> @hindawy1973</p>
			<p><strong>مكتب اليكس بروكرز للعقارات بالاسكندرية...</strong>
			نقدم لك خدمة التواصل مع أصحاب الشقق التمليك والمفروشة والقانون الجديد. وأيضاً الأراضي بمدينة الاسكندرية.</p>

			<p>عايز تمتلك شقة...عايز شقة إيجار مفروش...... عايز محل تبدأ فيه مشروعك...عايز أرض.
			إحنا حنوفر لك كل دة.</p>

			<p>من خلال تشكيلة واسعة من الشقق المفروشة الفاخرة ومن خلال الشقق إيجار قانون جديد أو التمليك.
			في أرقي الأماكن بالإسكندرية.

			أتصل بنا وإحنا نساعدك.</p>

			<p>مكتب اليكس بروكرز للعقارات بالاسكندرية...التسويق بمفهوم مختلف.</p>

				
			</div>
			
		</div>
		
		<div class="col-md-2" id="index-right">
			<h1>إعلانات</h1>
			<%= render 'partials/rightAd'%>
		</div>
		
</div>

app/views/pages/home.html.erb
<div>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</div>

<div id="myPage" data-spy="scroll" data-target=".navbar" data-offset="50">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="/images/alex5.jpg" alt="Alexandria">
        <div class="carousel-caption">
          <h3>الاسكندرية</h3>
          <p>عروس البحر المتوسط</p>
        </div>
      </div>
      
      <div class="item">
        <img src="/images/alex6.jpg" alt="Alexandria">
        <div class="carousel-caption">
          <h3>الاسكندرية</h3>
          <p>عروس البحر المتوسط</p>
        </div>
      </div>

      <div class="item">
        <img src="/images/alex7.jpg" alt="Alexandria">
        <div class="carousel-caption">
          <h3>الاسكندرية</h3>
          <p>عروس البحر المتوسط</p>
        </div>
      </div>

    <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  
  </div>  
  
<div id="first-ads" class="container text-center">
    <h3> اليكس بروكرز </h3>
    <p> اهلا بك في موقعنا </p>
    <p> نحن متخصصون في بيع وتاجير الشقق والعقارات بالاسكندرية</p>
    <br>
    <div>
      <div class="row">
        <div class="col-sm-4">
          <p class="text-center"><strong>2 عرض مميز</strong></p><br>
          <a href="#demo" data-toggle="collapse">
            <% if @awesomedAd[0].present? %>
                <%= image_tag(@awesomedAd[0].assets.first.image.url(:medium), :alt => "AlexBrokers", class: "img-circle alex") %>
            <% else %>
                <%=	image_tag('/images/alexbrokers4.jpg', class:'img-circle alex') %>
            <% end %>
          </a>
          <% if @awesomedAd[0].present? %>
              <div id="demo" class="collapse">
                <p><%= @awesomedAd[0].name %></p>
              </div>
          <% else %>
              <div id="demo" class="collapse">
                <p> اليكس بروكرز للتسويق العقاري </p>
                <p> اتصل بنا لتضع اعلانك هنا </p>
                <p> 0122-336-7978 <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></p>
                <p>hindawy1973@ <i class="fa fa-comment fa-lg" data-fa-transform="flip-v" aria-hidden="true"> </i></p>
              </div>
          <% end %>
        </div>
        
        <div class="col-sm-4">
          <p class="text-center"><strong>2 عرض مميز</strong></p><br>
          <a href="#demo2" data-toggle="collapse">
            <% if @awesomedAd[1].present? %>
                <%= image_tag(@awesomedAd[1].assets.first.image.url(:medium), :alt => "AlexBrokers", class: "img-circle alex") %>
            <% else %>
                <%=	image_tag('/images/alexbrokers4.jpg', class:'img-circle alex') %>
            <% end %>
          </a>
          <% if @awesomedAd[1].present? %>
              <div id="demo2" class="collapse">
                <p><%= @awesomedAd[1].name %></p>
              </div>
          <% else %>
              <div id="demo2" class="collapse">
                <p> اليكس بروكرز للتسويق العقاري </p>
                <p> اتصل بنا لتضع اعلانك هنا </p>
                <p> 0122-336-7978 <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></p>
                <p>hindawy1973@ <i class="fa fa-comment fa-lg" data-fa-transform="flip-v" aria-hidden="true"> </i></p>
              </div>
          <% end %>
        </div>

        <div class="col-sm-4">
          <p class="text-center"><strong>1 عرض مميز</strong></p><br>
          <a href="#demo3" data-toggle="collapse">
            <% if @awesomedAd[2].present? %>
                <%= image_tag(@awesomedAd[2].assets.first.image.url(:medium), :alt => "AlexBrokers", class: "img-circle alex") %>
            <% else %>
                <%=	image_tag('/images/alexbrokers4.jpg', class:'img-circle alex') %>
            <% end %>
          </a>
          <% if @awesomedAd[2].present? %>
              <div id="demo3" class="collapse">
                <p><%= @awesomedAd[2].name %></p>
              </div>
          <% else %>
              <div id="demo3" class="collapse">
                <p> اليكس بروكرز للتسويق العقاري </p>
                <p> اتصل بنا لتضع اعلانك هنا </p>
                <p> 0122-336-7978 <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></p>
                <p>hindawy1973@ <i class="fa fa-comment fa-lg" data-fa-transform="flip-v" aria-hidden="true"> </i></p>
              </div>
          <% end %>
        </div>
      </div>
    </div>
</div>
  
  <div id="souq" class="bg-1">
    <div class="container">
      <div id="souq-header">
      	<h3 class="text-center"> عروض جديدة </h3>
      	<p class="text-center"> اجدد الاعلانات تجدها هنا </p>
			</div>
      <ul class="list-group">
        <li class="list-group-item"> <i class="fa fa-circle" aria-hidden="true"></i> <%= @latestAd[0].name %>  <%= link_to ' التفاصيل ', @latestAd[0] %> </li>
        <li class="list-group-item"> <i class="fa fa-circle" aria-hidden="true"></i> <%= @latestAd[1].name %>  <%= link_to ' التفاصيل ', @latestAd[1] %> </li>
        <li class="list-group-item"> <i class="fa fa-circle" aria-hidden="true"></i> <%= @latestAd[2].name %>  <%= link_to ' التفاصيل ', @latestAd[2] %> </li>
      </ul>
    </div>
  
    <div class="row text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <% if @greatedAd[0].present? %>
            <%= image_tag(@greatedAd[0].assets.first.image.url(:medium)) %>
          <p><strong>فرصة</strong></p>
          <p><%= @greatedAd[0].name %> </p>
          <button class="btn"><%= link_to 'التفاصيل', @greatedAd[0]%></button>
        <% else %>
            <%=	image_tag('/images/alexbrokers4.jpg', class:'img-circle alex') %>
            <p><strong>فرصة</strong></p>
            <p> اليكس بروكرز للتسويق العقاري </p>
            <p> اتصل بنا لتضع اعلانك هنا </p>
            <p> 0122-336-7978 <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></p>
            <p>hindawy1973@ <i class="fa fa-comment fa-lg" data-fa-transform="flip-v" aria-hidden="true"> </i></p>
        <% end %>
      </div>
    </div>
    <div class="col-sm-4">
        <div class="thumbnail">
          <% if @greatedAd[1].present? %>
              <%= image_tag(@greatedAd[1].assets.first.image.url(:medium)) %>
              <p><strong>فرصة</strong></p>
              <p><%= @greatedAd[1].name %> </p>
              <button class="btn"><%= link_to 'التفاصيل', @greatedAd[1]%></button>
          <% else %>
              <%=	image_tag('/images/alexbrokers4.jpg', class:'img-circle alex') %>
              <p><strong>فرصة</strong></p>
              <p> اليكس بروكرز للتسويق العقاري </p>
              <p> اتصل بنا لتضع اعلانك هنا </p>
              <p> 0122-336-7978 <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></p>
              <p>hindawy1973@ <i class="fa fa-comment fa-lg" data-fa-transform="flip-v" aria-hidden="true"> </i></p>
          <% end %>
        </div>
      </div>
    <div class="col-sm-4">
        <div class="thumbnail">
          <% if @greatedAd[2].present? %>
              <%= image_tag(@greatedAd[2].assets.first.image.url(:medium)) %>
              <p><strong>فرصة</strong></p>
              <p><%= @greatedAd[2].name %> </p>
              <button class="btn"><%= link_to 'التفاصيل', @greatedAd[2]%></button>
          <% else %>
              <%=	image_tag('/images/alexbrokers4.jpg', class:'img-circle alex') %>
              <p><strong>فرصة</strong></p>
              <p> اليكس بروكرز للتسويق العقاري </p>
              <p> اتصل بنا لتضع اعلانك هنا </p>
              <p> 0122-336-7978 <i class="fa fa-phone-square fa-lg" aria-hidden="true"></i> <i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></p>
              <p>hindawy1973@ <i class="fa fa-comment fa-lg" data-fa-transform="flip-v" aria-hidden="true"> </i></p>
          <% end %>
        </div>
      </div>

    <!--<div class="col-sm-4">-->
      <!--<div class="thumbnail">-->
        <!--<img src="/images/alex2.jpg" alt="New York">-->
        <!--<p><strong>اعلان 2</strong></p>-->
        <!--<p>نبذة عن الاعلان</p>-->
        <!--<button class="btn">المزيد</button>-->
      <!--</div>-->
    <!--</div>-->
    <!--<div class="col-sm-4">-->
      <!--<div class="thumbnail">-->
        <!--<img src="/images/alex3.jpg" alt="San Francisco">-->
        <!--<p><strong>اعلان 3</strong></p>-->
        <!--<p>نبذة عن الاعلان</p>-->
        <!--<button class="btn">تفاصيل</button>-->
      <!--</div>-->
      <!--</div>-->
  <!---->
  
  </div>


  
  </div>

  </div>

 <!-- </html>
-->

app/views/pages/home2.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/partials/_leftAd.html.erb
      <% @leftAd.each do |leftAd|%>
             <% if leftAd.assets.exists? %>
							<div class='margin-ads'>
								<%= link_to image_tag(leftAd.assets.first.image.url(:thumb), class:"generalAds-Image"), leftAd %>
								<p><%= leftAd.name %></p>
							</div>
						<% else %>
							<div class='margin-ads'>
								<%= link_to image_tag('/images/genImage_thumb.jpg', class:'generalAds-Image'), leftAd%>
								<p><%= leftAd.name %></p>
            	</div>
            <% end %>
      <% end %>

      <% if @leftAd.length < 5 %>
          <% generalAdsLength = 5-@leftAd.length %>
          <% for generalAds in 1..generalAdsLength %>
             	<div class='margin-ads'>
              	<%=	link_to image_tag('/images/alexbrokers4.jpg', class:'generalAds-Image'), about_path %>
              	<p>اتصل بنا</p>
              </div>
          <% end %>
      <% end %>

app/views/partials/_navbar.html.erb
  <nav class="navbar navbar-default transparent navbar-fixed-top " data-turbolinks="false">
		<div class="navbar-inner ">

		 <div class="navbar-header pull-right">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">اظهار القائمة</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/"><h1>اليكس بروكرز</h1></a>
			</div>		
		
		
			<div id="navbar" class="collapse navbar-collapse pull-right">
				<ul class="nav navbar-nav">
					
					<li><%=link_to "عن الموقع", about_path%></li>

					<% if user_signed_in? %>
						<% if current_user.privateUser? %>
							<li class="dropdown">
								<%= link_to "", {'class'=>"dropdown-toggle", 'data-toggle'=>"dropdown", 'role'=>"button", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"} do %>
								 العقارات الخاصة<span class="caret"></span>
								<% end %>
								<ul class="dropdown-menu">
									<%= link_to ' كل العقارات الخاصة', private_realty_index_path %><br/>
									<% Type.all.each do |type| %>
										<%= link_to type.name, private_realty_index_path(:type_id => type.id)  %><br/>
									<% end %>
								</ul>
							</li>
						<% end %>

					
					<li>								
								<%= link_to 'اضافة إعلان', realties_new_path %>
					</li>
					
					<% end %>
<!--
					<li class="active"><%#=link_to "العقارات", realties_index_path%></li>
					<li class="dropdown"><a href="#">More<span class="caret"></span></a></li>
-->
					<li class="dropdown">
   					<%= link_to "", {'class'=>"dropdown-toggle", 'data-toggle'=>"dropdown", 'role'=>"button", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"} do %>
    					العقارات<span class="caret"></span>
						<% end %>
						<ul class="dropdown-menu">
							<%= link_to 'كل العقارات', realties_index_path %><br/>
							<% Type.all.each do |type| %>
								<%= link_to type.name, realties_index_path(:type_id => type.id)  %><br/>
							<% end %>
          	</ul>
					
					</li>
				</ul>

			</div>

			<!--/.nav-collapse -->
			
			<div id='container'>
				<!-- Alerts & Messages -->
				<div id="notice-alert">
					<% if flash[:notice] %>
						<div class="alert alert-success"><%= flash[:notice] %></div>
					<% end %>

					<% if flash[:alert] %>
						<div class="alert alert-danger"><%= flash[:alert] %></div>
					<% end %>
				</div>
				<!-- user logging message-->
				<div>
					<div id="user_nav">
						<% if user_signed_in? %>
								تم تسجيل الدخول باسم: <%= link_to current_user.email, user_path(current_user) %> 
								<%= link_to "تسجيل خروج", destroy_user_session_path, :method => :delete, :style => "float: left;" %>
						<% else %>
								<%= link_to 'مستخدم جديد', new_user_registration_path %> او <%= link_to 'تسجيل دخول',  new_user_session_path %>
						<% end %>
					</div>
				</div>
				
			</div>
			
		</div>
	</nav>

app/views/partials/_rightAd.html.erb
		<% @rightAd.each do |rightAd|%>
          <% if rightAd.assets.exists? %>
          	<div  class="margin-ads">
							<%= link_to image_tag(rightAd.assets.first.image.url(:thumb), class:"generalAds-Image"), rightAd %>
							<p><%= rightAd.name %></p>
						</div>
					<% else %>
						<div class='margin-ads'>
          		<%= link_to image_tag('/images/genImage_thumb.jpg', class:'generalAds-Image'), rightAd%>
           		<p><%= rightAd.name %></p>
          	</div>
          <% end %>
      <% end %>

      <% if @rightAd.length < 5 %>
          <% generalAdsLength = 5-@rightAd.length %>
          <% for generalAds in 1..generalAdsLength %>
              <div class='margin-ads'>
              	<%=	link_to image_tag('/images/alexbrokers4.jpg', class:'generalAds-Image'), about_path %>
              	<p>اتصل بنا</p>
              </div>
          <% end %>
      <% end %>

app/views/partials/_search.html.erb

<div id="search-form" >

	<%= search_form_for @q do |f|%>
		<h3>ابحث عن اعلان</h3>
		<div class="form-group search-group" id="search_partial">
			<%= f.text_field :name_cont, placeholder: "في العنوان", class: 'form-control' %>

			<%= f.select :type_id_eq, Type.all.collect {|x| [x.name, x.id]}, {:include_blank => 'النوع'} , class: 'form-control', :style => "width: 194px;" %>

			<%= f.select :category_id_eq, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'الفئة'} , class: 'form-control', :style => "width: 194px;" %>

			<div>
				<%= f.number_field :price_gteq, step: 100, placeholder: 'السعر من', class: 'form-control-fromto'%>
				<%= f.number_field :price_lteq, step: 100, placeholder: 'السعر الى', class: 'form-control-fromto'%>
			</div>

			<%= f.select :governorate_id_eq, Governorate.all.collect {|x| [x.name, x.id]}, {:include_blank => 'اختار المحافظة'}, class: 'form-control', id: 'searchGovernorateID', :style => "width: 194px;" %>

			<%= f.grouped_collection_select :province_id_eq, Governorate.order(:name), :provinces, :name, :id, :name, {:include_blank => 'اختار الحي'}, class: 'form-control' , id: 'searchProvinceID', :style => "width: 194px;" %>

			<div>		
				<%= f.number_field :size_gteq, step: 10, placeholder: 'مساحة من', class: 'form-control-fromto'%>
				<%= f.number_field :size_lteq, step: 10, placeholder: 'مساحة الى', class: 'form-control-fromto'%>
			</div>

			<div>		
				<%= f.number_field :floor_gteq, in: 1...50, step: 1, placeholder: 'الدور من', class: 'form-control-fromto'%>
				<%= f.number_field :floor_lteq, in: 1...50, step: 1, placeholder: 'الدور الى', class: 'form-control-fromto'%>
			</div>		

			<div>
				<%= f.number_field :rooms_gteq, in:1...20, step: 1, placeholder: 'الغرف من', class: 'form-control-fromto'%>
				<%= f.number_field :rooms_lteq, in:1...20, step: 1, placeholder: 'الغرف الى', class: 'form-control-fromto'%>
			</div>

			<div>
				<%= f.number_field :baths_gteq, in: 1...10, step: 1, placeholder: 'حمامات من', class: 'form-control-fromto'%>
				<%= f.number_field :baths_lteq, in: 1...10, step: 1, placeholder: 'حمامات الى', class: 'form-control-fromto'%>
			</div>


			<%#= f.text_area :details, class: 'form-control' %>

		</div>

		<%= f.submit "بـحث", class: 'btn-primary btn-sm search-btn'%>


	<% end %>

</div>