config/routes.rb
Rails.application.routes.draw do
  get 'private_realty/new'

  get 'private_realty/create'

  get 'private_realty/edit'

  get 'private_realty/update'

  get 'private_realty/index'

  get 'private_realty/show'

  get 'private_realty/destroy'

#  get 'users/show'
#
#  get 'users/edit'
#
#  get 'users/update'

	
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'realties/new'

  get 'realties/create'

  get 'realties/edit'

  get 'realties/update'

  get 'realties/index'

  get 'realties/show'

  get 'realties/destroy'

  root 'pages#home'

  get 'about' => 'pages#about'
	
	resources :realties
	resources :users
	resources :private_realty
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :realty

	has_attached_file :image,
                    styles: {medium: '200x250!', thumb: '100x100!'},
										:default_url => "path to default image"
										#:default_url => "genImage.jpg"
										#default_url: ->(attachment) { ActionController::Base.helpers.asset_path('genImage.jpg') }
										#:default_url => ActionController::Base.helpers.image_path("genImage.jpg")
										#default_url: ":style/genImage.jpg"
	
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	#validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/governorate.rb
class Governorate < ApplicationRecord
	has_many :provinces
	has_many :realties
end

app/models/luxury.rb
class Luxury < ApplicationRecord
	
	has_many :realty_luxuries, dependent: :destroy #, inverse_of: :luxury
	has_many :realties, through: :realty_luxuries#, source: :realty
	
	#accepts_nested_attributes_for :realty_luxuries
end

app/models/province.rb
class Province < ApplicationRecord
	
	belongs_to :governorate
	has_many :realties
	
end

app/models/realty.rb
class Realty < ApplicationRecord

	belongs_to :governorate
	belongs_to :province
	#belongs_to :luxury
	belongs_to :type
	belongs_to :category
	belongs_to :user
	
	has_many :assets, dependent: :destroy
	
	has_many :realty_luxuries, dependent: :destroy #, inverse_of: :realty
	has_many :luxuries, through: :realty_luxuries
	
	accepts_nested_attributes_for :assets, :reject_if => lambda { |t| t['image'].nil? }, allow_destroy: true
	


end

app/models/realty_luxury.rb
class RealtyLuxury < ApplicationRecord
  belongs_to :realty#, inverse_of: :realty_luxuries
  belongs_to :luxury#, inverse_of: :realty_luxuries
	
	#accepts_nested_attributes_for :luxury
    
end

app/models/type.rb
class Type < ApplicationRecord
	
	has_many :realties
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :timeoutable
	
	has_many :realties
	
#	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
#	#, :default_url => "/images/:style/missing.png"
#  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	
	def display_name
 		return self.email
	end
	
#  def password_required?
#    if respond_to?(:reset_password_token)
#      return true if reset_password_token.present?
#    end
#    return true if new_record?
#    password.present? || password_confirmation.present?
#  end
	
def password_required?
  new_record? || password.present? || password_confirmation.present?
end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @awesomedAd = Realty.where('awesomed=True')
    @greatedAd = Realty.where('greated=True')
    @latestAd = Realty.order('created_at DESC').limit(3)
  end

  def about
		@rightAd = Realty.where("righted = True").where('privateRealties=false')
		@leftAd = Realty.where("lefted = True").where('privateRealties=false')
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :authenticate_user!, except: [ :show]
  def show
		@user = User.find(params[:id])
		@user_realties = @user.realties.order('created_at DESC').paginate(page: params[:page], per_page: 10)
		@rightAd = Realty.where("righted = True")
		@leftAd = Realty.where("lefted = True")
  end

  def edit
		@rightAd = Realty.where("righted = True")
		@leftAd = Realty.where("lefted = True")
  end

  def update
  	@rightAd = Realty.where("righted = True")
		@leftAd = Realty.where("lefted = True")
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/governorates_helper.rb
module GovernoratesHelper
end

app/helpers/luxuries_helper.rb
module LuxuriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/realties_helper.rb
module RealtiesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<!-- User profile show page -->

<div class="row" >

		<div class="col-md-2 left">
			<h1>إعلانات</h1>
      <% @leftAd.each do |leftAd|%>
          <div  class="margin-ads">
            <% if leftAd.assets.exists? %>
                <%= link_to image_tag(leftAd.assets.first.image.url(:thumb), class:"ads-Image"), leftAd %>
                <p><%= leftAd.name %></p>
            <% end %>
          </div>
      <% end %>

      <% if @leftAd.length < 5 %>
          <% generalAdsLength = 5-@leftAd.length %>
          <% for generalAds in 1..generalAdsLength %>
              <%=	link_to image_tag('/images/alexbrokers4.jpg', class:'generalAds-Image'), about_path %>
          <% end %>
      <% end %>
		</div>
		
		<div class="col-md-8 middle">

				<% if @user == current_user %>
					<h1>اهلا بك: <%= @user.username%></h1>
					<%= link_to "تعديل الملف الشخصي", edit_user_registration_path %><br/>
					<%= link_to "اعادة ارسال كود التفعيل", new_user_confirmation_path %>
				<% end %>
			
			<table class="table" id="user-details">
				<tr>
					<td><strong>الاسم: </strong></td>
					<td><%= @user.username%></td>
				</tr>
				<tr>
					<td><strong>البريد الاليكتروني: </strong></td>
					<td><%= @user.email%></td>
				</tr>
				<tr>
					<td><strong>رقم الهاتف: </strong></td>
					<td><%= @user.mob%></td>
				</tr>
			</table>			
			
			
			<table class="table">
				<thead>
					<tr>
						<th>العقار</th>
						<th>تاريخ الاعلان</th>
						<th>النوع</th>
						<th>المحافظة</th>
						<th>الحي</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @user_realties.each do |urealty| %>
						<tr>
							<td id="user-table-realty-name"><%= link_to urealty.name, realty_path(urealty) %></td>
							<td><%= I18n.localize(urealty.created_at, :format =>  '%e %B %Y')%></td>
							<td><%= urealty.type.name %></td>
							<td><%= urealty.governorate.name %></td>
							<td><%= urealty.province.name %></td>
							<% if user_signed_in? %>
								<% if urealty.user == current_user %>
									<td><%= link_to 'تعديل', edit_realty_path(urealty) %></td>
									<td><%= link_to 'حذف', urealty, method: :delete, data: { confirm: 'هل انت متأكد؟' } %></td>
								<% end %>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>			
					
		<br />
				      <div class="apple_pagination">
        <!--div class="page_info">
          <%#= page_entries_info @realties %>
        </div-->
        <%= will_paginate @user_realties, previous_label: h("< السابق "), next_label: h("التالي >"), :container => false, :style => 'direction:rtl' %>

      </div>
		
		</div>
	
			<div class="col-md-2 right">
			<h1>إعلانات</h1>
			<% @rightAd.each do |rightAd|%>
          <div  class="margin-ads">
            <% if rightAd.assets.exists? %>
                <%= link_to image_tag(rightAd.assets.first.image.url(:thumb), class:"ads-Image"), rightAd %>
                <p><%= rightAd.name %></p>
            <% end %>
          </div>
      <% end %>

      <% if @leftAd.length < 5 %>
          <% generalAdsLength = 5-@leftAd.length %>
          <% for generalAds in 1..generalAdsLength %>
              <%=	link_to image_tag('/images/alexbrokers4.jpg', class:'generalAds-Image'), about_path %>
          <% end %>
      <% end %>
		</div>
		
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>